author: Minor Gordon
branding:
  icon: loader
description: Extract, transform, and load data from files in a directory.
inputs:
  cache_directory_path:
    default: _cache
    description: Path to a directory in which to store cached data
    required: false
  debug:
    description: Debug the action
    required: false
  directory_path:
    default: .
    description: Path to a directory of Markdown files
    required: false
  loaded_data_directory_path:
    default: _data
    description: Path to a directory in which to store the loaded RDF file
    required: false
  loaded_data_file_path:
    description: Path to a file in which to store the loaded RDF, overrides data_directory_path
      if specified
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
name: Extract, transform, and load data from files in a directory.
runs:
  image: Dockerfile
  using: docker
