author: Minor Gordon
branding:
  icon: loader
description: Extract, transform, and load data from a Paradicms Markdown directory.
inputs:
  data_directory_path:
    default: _data
    description: Path to a directory where extracted/ and loaded/ data should be stored
    required: false
  debug:
    description: Debug the action
    required: false
  markdown_directory_path:
    default: .
    description: Path to a directory of Markdown files
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
name: Extract, transform, and load data from a Paradicms Markdown directory.
runs:
  image: Dockerfile
  using: docker
