name: "Generate a static site from a Paradicms-formatted spreadsheet"
description: "Generate a static site from a Paradicms-formatted spreadsheet"
author: "Minor Gordon"
branding:
  icon: "loader"
inputs:
  app_configuration_file_path:
    description: Path to an app configuration file, which controls the static site generator
    required: false
  debug:
    description: Debug the action
    required: false
  markdown_directory_path:
    default: "."
    description: Path to a directory of Markdown files, defaults to the current directory
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
